---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: missionstages.airforce.airforce.mil
spec:
  group: airforce.airforce.mil
  names:
    kind: MissionStage
    listKind: MissionStageList
    plural: missionstages
    shortNames:
    - ms
    singular: missionstage
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Status phase
      jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: MissionStage is the Schema for the missionstages API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: MissionStageSpec defines the desired state of MissionStage
            properties:
              config:
                properties:
                  dependencies:
                    properties:
                      conditions:
                        items:
                          properties:
                            type:
                              type: string
                          type: object
                        type: array
                    type: object
                  synchronization:
                    properties:
                      checkpoint:
                        type: string
                      waitForAll:
                        type: boolean
                    type: object
                  timeout:
                    type: string
                type: object
              dependsOn:
                items:
                  type: string
                type: array
              flightTasks:
                items:
                  properties:
                    aircraft:
                      type: string
                    name:
                      type: string
                    podTemplate:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    priority:
                      type: string
                    role:
                      type: string
                    taskParams:
                      additionalProperties:
                        type: string
                      type: object
                    weaponLoadout:
                      items:
                        properties:
                          mountPoints:
                            items:
                              type: string
                            type: array
                          quantity:
                            format: int32
                            type: integer
                          weapon:
                            type: string
                        type: object
                      type: array
                  type: object
                type: array
              missionRef:
                properties:
                  name:
                    type: string
                type: object
              stageIndex:
                format: int32
                type: integer
              stageName:
                type: string
              stageType:
                enum:
                - sequential
                - parallel
                - mixed
                type: string
            type: object
          status:
            description: MissionStageStatus defines the observed state of MissionStage
            properties:
              completionTime:
                format: date-time
                type: string
              flightTasksStatus:
                items:
                  properties:
                    aircraftNode:
                      type: string
                    message:
                      type: string
                    name:
                      type: string
                    phase:
                      type: string
                    podName:
                      type: string
                  type: object
                type: array
              message:
                type: string
              phase:
                enum:
                - Pending
                - Running
                - Succeeded
                - Failed
                type: string
              startTime:
                format: date-time
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
