# permissions for end users to view missionstages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: missionstage-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: airforce-mission-system
    app.kubernetes.io/part-of: airforce-mission-system
    app.kubernetes.io/managed-by: kustomize
  name: missionstage-viewer-role
rules:
- apiGroups:
  - airforce.airforce.mil
  resources:
  - missionstages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - airforce.airforce.mil
  resources:
  - missionstages/status
  verbs:
  - get
