# permissions for end users to edit weapons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: weapon-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: airforce-mission-system
    app.kubernetes.io/part-of: airforce-mission-system
    app.kubernetes.io/managed-by: kustomize
  name: weapon-editor-role
rules:
- apiGroups:
  - airforce.airforce.mil
  resources:
  - weapons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - airforce.airforce.mil
  resources:
  - weapons/status
  verbs:
  - get
